name: GitHub Account Manager

on:
  workflow_dispatch:
    inputs:
      target_account:
        description: "Target GitHub username/org"
        required: true
      operation:
        description: "Operation (list_repos, create_repo, delete_repo, toggle_visibility, create_release)"
        required: true
        default: "list_repos"
      repo_name:
        description: "Repository name"
        required: false
      tag_name:
        description: "Tag name for release (required for create_release)"
        required: false
      release_title:
        description: "Release title (required for create_release)"
        required: false
      asset_url:
        description: "Download URL for release asset (optional for create_release)"
        required: false

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run control script
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_TOKEN }}
          TARGET_ACCOUNT: ${{ inputs.target_account }}
          OPERATION: ${{ inputs.operation }}
          REPO_NAME: ${{ inputs.repo_name }}
          TAG_NAME: ${{ inputs.tag_name }}
          RELEASE_TITLE: ${{ inputs.release_title }}
          ASSET_URL: ${{ inputs.asset_url }}
        run: python github_manager.py
