name: GitHub Account Manager

on:
  workflow_dispatch:
    inputs:
      target_account:
        description: "Target GitHub username/org"
        required: true
      operation:
        description: "Operation (list_repos, create_repo, delete_repo, toggle_visibility)"
        required: true
        default: "list_repos"
      repo_name:
        description: "Repository name (for create/delete/toggle)"
        required: false

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run control script
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_TOKEN }}
          TARGET_ACCOUNT: ${{ inputs.target_account }}
          OPERATION: ${{ inputs.operation }}
          REPO_NAME: ${{ inputs.repo_name }}
        run: python github_manager.py
